# Generated by Django 2.0 on 2018-01-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='focusedquestion',
            field=models.ManyToManyField(to='default.Question'),
        ),
    ]
