# Generated by Django 2.0 on 2018-01-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_question_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerNum',
            field=models.IntegerField(default=0),
        ),
    ]
