# Generated by Django 2.0 on 2018-01-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0008_question_answernum'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='img',
            field=models.ImageField(blank=True, default='/upload/empty.png', upload_to='upload'),
        ),
    ]
