# Generated by Django 2.0 on 2018-01-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0009_answer_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='img',
        ),
    ]
