# Generated by Django 2.0 on 2018-01-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0011_answer_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='focus',
            field=models.IntegerField(default=0),
        ),
    ]
